name: build_docs.yml
on:
  push:
    branches:
      - main
      - napytau/tooling/add-documentation-framework
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install Python
        run: uv python install
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Build documentation
        run: cd docs && mkdocs gh-deploy --force
