name: ci
run-name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  install-dependencies:
    runs-on: ubuntu-latest
    needs: checkout-code
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Set up Python
        run: uv python install
      - name: Install dependencies
        run: uv sync --all-extras --dev

  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Lint
        run: uvx tomlscript lint

  run-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Run tests
        run: uvx tomlscript test